#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]

colorscheme = "gruvbox"
# colorscheme = "dracula"
colorscheme_bg = "dark"

enable_guicolors = true

statusline_separator = "arrow"
statusline_inactive_separator = "bar"
statusline_unicode_symbols = true

# 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
# 0: 1 ➛ ➊
# 1: 1 ➛ ➀
# 2: 1 ➛ ⓵
# 3: 1 ➛ ¹
# 4: 1 ➛ 1
buffer_index_type = 1
windows_index_type = 4

enable_tabline_filetype_icon = true
enable_statusline_mode = false

vimcompatible = false

# filemanager = "defx"

bootstrap_after = "younger#after"
bootstrap_before = "younger#before"


# SpaceVim 模块设置，主要包括启用/禁用模块

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#rust"
format_on_save = 1

[[layers]]
name = "lang#c"
format_on_save = 1

[[layers]]
name = "lang#python"
format_on_save = 1
python_file_head = ['#!/usr/bin/env python', '# -*- coding: utf-8 -*-', '', '']

[[layers]]
name = "lang#java"
format_on_save = 1
java_file_head = [
  '/**',
  ' * @author : `fnamemodify(expand("~"), ":t")`',
  ' * @created : `strftime("%Y-%m-%d")`',
  '**/',
  '',
]
# java_fomatter_jar = 'path/to/google-java-format.jar'


[[layers]]
name = "lang#markdown"
format_on_save = 1

[[layers]]
name = "lsp"
filetypes = ["java"]

[layers.override_cmd]
java = [
  "java",
  "-Declipse.application=org.eclipse.jdt.ls.core.id1",
  "-Dosgi.bundles.defaultStartLevel=4",
  "-Declipse.product=org.eclipse.jdt.ls.core.product",
  "-Dlog.protocol=true",
  "-Dlog.level=NONE",
  "-noverify",
  "-Xmx1G",
  "-jar",
  "C:/Users/younger/.vscode/extensions/redhat.java-0.73.0/server/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar",
  "-configuration",
  "C:/Users/younger/.vscode/extensions/redhat.java-0.73.0/server/config_win",
  "-data",
  "C:\\Users\\younger\\.cache\\javalsp",
]

# [[layers]]
# name = "format"

# [[layers]]
# name = "debug"

# [[layers]]
# name = "denite"

# [[custom_plugins]]
# repo = "CoatiSoftware/vim-sourcetrail"
# merged = false

# [[custom_plugins]]
# repo = "wsdjeg/mdctags.rs"
# merged = false

[[custom_plugins]]
repo = "dracula/vim"
name = "dracula"
merged = false

